# Generated by Django 2.2.15 on 2020-08-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe/'),
        ),
    ]
