# Generated by Django 2.2.15 on 2020-08-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_auto_20200814_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeplan',
            name='meal_name',
        ),
        migrations.AddField(
            model_name='recipeplan',
            name='meal_name',
            field=models.IntegerField(choices=[(0, 'Śniadanie'), (1, 'Drugie Śniadanie'), (2, 'Obiad'), (3, 'Podwieczorek'), (3, 'Kolacja')], default=0),
        ),
    ]
