# Generated by Django 2.2.15 on 2020-08-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_auto_20200814_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeplan',
            name='meal_name',
            field=models.CharField(max_length=255),
        ),
    ]
